# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# What is the name of this workflow?
name: .NET

# When does this run?
on:
# Run whenever there is a push to main branch
  push:
    branches: [ "main", "additional-branch" ]
  # Run whenever there is a PR merging to main
  pull_request:
    branches: [ "main" ]
  # Manually trigger this workflow
  workflow_dispatch:
env: 
  WORKING_DIR: "TickProject/Tick.App"
# What should this pipeline workflow do?
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: 'TickProject/Tick.App' # Ensure this path is correctly set relative to the root of your GitHub repository
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' # Specify the .NET version you are using
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIR}}
